In [1]:
import pandas as pd
import numpy as np
import warnings
import nltk
warnings.filterwarnings("ignore")

In [77]:
df=pd.read_csv('tmdb_5000_movies.csv')
cre=pd.read_csv('tmdb_5000_credits.csv')

In [78]:
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [79]:
cre.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [80]:
# merge two tables

movie=df.merge(cre,on='title')

In [81]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [82]:
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

In [83]:
movie = movie[['movie_id','title','overview','genres','keywords','cast','crew']]

In [84]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
import ast

In [11]:
def recommend(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [12]:
movie['genres']=movie['genres'].apply(recommend)

In [13]:
movie['keywords']=movie['keywords'].apply(recommend)

In [14]:
movie['cast']=movie['cast'].apply(recommend)

In [15]:
movie['cast']=movie['cast'].apply(lambda x:x[0:3])

In [16]:
def crew_fetch(text):
    L=[]
    for i in ast.literal_eval(text):
        if i["job"]=="Director":
            L.append(i['name'])
    return L

In [17]:
movie['crew']=movie['crew'].apply(crew_fetch)

In [18]:
def space_replace(text):
    L1=[]
    for i in text:
        L1.append(i.replace(" ",""))
    return L1

In [19]:
movie['genres']=movie['genres'].apply(space_replace)
movie['keywords']=movie['keywords'].apply(space_replace)
movie['cast']=movie['cast'].apply(space_replace)
movie['crew']=movie['crew'].apply(space_replace)

In [20]:
movie.dropna(inplace=True)

In [21]:
movie['overview']=movie['overview'].apply(lambda x:x.split())

In [22]:
movie['tags'] = movie['overview'] + movie['genres'] + movie['keywords'] + movie['cast'] + movie['crew']

In [23]:
movie['tags']=movie['tags'].apply(lambda x:' '.join(x))

In [24]:
new = movie.drop(columns=['overview','genres','keywords','cast','crew'])

In [25]:
from nltk.stem.porter import PorterStemmer

In [26]:
ps=PorterStemmer()

In [28]:
new['tags']=new['tags'].apply(lambda x:x.split())

In [30]:
new['tags']=new['tags'].apply(lambda x:[ps.stem(word) for word in x])

In [32]:
new['tags']=new['tags'].apply(lambda x:' '.join(x))

In [36]:
new['tags']=new['tags'].apply(lambda x:x.lower())

# Model building

In [38]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [39]:
cv=CountVectorizer(max_features=5000)
tfidf=TfidfVectorizer(max_features=5000)

In [41]:
x=cv.fit_transform(new['tags']).toarray()

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity=cosine_similarity(x)

In [49]:
new[new['title']=='Avatar'].index[0]

np.int64(0)

In [62]:
def recommends(movie):
    index = new[new['title'] == movie].index[0]

    distance = sorted(
        list(enumerate(similarity[index])),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in distance[1:6]:
        print(new.iloc[i[0]].title)

In [74]:
recommends('Battleship')

The Work and the Glory II: American Zion
Ironclad
Conan the Barbarian
Jack the Giant Slayer
Once in a Lifetime: The Extraordinary Story of the New York Cosmos

# same model

In [91]:
import pickle

In [92]:
pickle.dump(new,open('movie_list_pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))